### Spark notebook ###

This notebook will only work in a Jupyter notebook or Jupyter lab session running on the cluster master node in the cloud.

Follow the instructions on the computing resources page to start a cluster and open this notebook.

**Steps**

1. Connect to the Windows server using Windows App.
2. Connect to Kubernetes.
3. Start Jupyter and open this notebook from Jupyter in order to connect to Spark.

In [1]:
# Run this cell to import pyspark and to define start_spark() and stop_spark()

import findspark

findspark.init()

import getpass
import pandas
import pyspark
import random
import re

from IPython.display import display, HTML
from pyspark import SparkContext
from pyspark.sql import SparkSession


# Constants used to interact with Azure Blob Storage using the hdfs command or Spark

global username

username = re.sub('@.*', '', getpass.getuser())

global azure_account_name
global azure_data_container_name
global azure_user_container_name
global azure_user_token

azure_account_name = "madsstorage002"
azure_data_container_name = "campus-data"
azure_user_container_name = "campus-user"
azure_user_token = r"sp=racwdl&st=2025-08-01T09:41:33Z&se=2026-12-30T16:56:33Z&spr=https&sv=2024-11-04&sr=c&sig=GzR1hq7EJ0lRHj92oDO1MBNjkc602nrpfB5H8Cl7FFY%3D"


# Functions used below

def dict_to_html(d):
    """Convert a Python dictionary into a two column table for display.
    """

    html = []

    html.append(f'<table width="100%" style="width:100%; font-family: monospace;">')
    for k, v in d.items():
        html.append(f'<tr><td style="text-align:left;">{k}</td><td>{v}</td></tr>')
    html.append(f'</table>')

    return ''.join(html)


def show_as_html(df, n=20):
    """Leverage existing pandas jupyter integration to show a spark dataframe as html.
    
    Args:
        n (int): number of rows to show (default: 20)
    """

    display(df.limit(n).toPandas())

    
def display_spark():
    """Display the status of the active Spark session if one is currently running.
    """
    
    if 'spark' in globals() and 'sc' in globals():

        name = sc.getConf().get("spark.app.name")

        html = [
            f'<p><b>Spark</b></p>',
            f'<p>The spark session is <b><span style="color:green">active</span></b>, look for <code>{name}</code> under the running applications section in the Spark UI.</p>',
            f'<ul>',
            f'<li><a href="http://localhost:{sc.uiWebUrl.split(":")[-1]}" target="_blank">Spark Application UI</a></li>',
            f'</ul>',
            f'<p><b>Config</b></p>',
            dict_to_html(dict(sc.getConf().getAll())),
            f'<p><b>Notes</b></p>',
            f'<ul>',
            f'<li>The spark session <code>spark</code> and spark context <code>sc</code> global variables have been defined by <code>start_spark()</code>.</li>',
            f'<li>Please run <code>stop_spark()</code> before closing the notebook or restarting the kernel or kill <code>{name}</code> by hand using the link in the Spark UI.</li>',
            f'</ul>',
        ]
        display(HTML(''.join(html)))
        
    else:
        
        html = [
            f'<p><b>Spark</b></p>',
            f'<p>The spark session is <b><span style="color:red">stopped</span></b>, confirm that <code>{username} (notebook)</code> is under the completed applications section in the Spark UI.</p>',
            f'<ul>',
            f'<li><a href="http://mathmadslinux2p.canterbury.ac.nz:8080/" target="_blank">Spark UI</a></li>',
            f'</ul>',
        ]
        display(HTML(''.join(html)))


# Functions to start and stop spark

def start_spark(executor_instances=4, executor_cores=2, worker_memory=2, master_memory=2):
    """Start a new Spark session and define globals for SparkSession (spark) and SparkContext (sc).
    
    Args:
        executor_instances (int): number of executors (default: 2)
        executor_cores (int): number of cores per executor (default: 1)
        worker_memory (float): worker memory (default: 1)
        master_memory (float): master memory (default: 1)
    """

    global spark
    global sc

    cores = executor_instances * executor_cores
    partitions = cores * 4
    port = 4000 + random.randint(1, 999)

    spark = (
        SparkSession.builder
        .config("spark.driver.extraJavaOptions", f"-Dderby.system.home=/tmp/{username}/spark/")
        .config("spark.dynamicAllocation.enabled", "false")
        .config("spark.executor.instances", str(executor_instances))
        .config("spark.executor.cores", str(executor_cores))
        .config("spark.cores.max", str(cores))
        .config("spark.driver.memory", f'{master_memory}g')
        .config("spark.executor.memory", f'{worker_memory}g')
        .config("spark.driver.maxResultSize", "0")
        .config("spark.sql.shuffle.partitions", str(partitions))
        .config("spark.kubernetes.container.image", "madsregistry001.azurecr.io/hadoop-spark:v3.3.5-openjdk-8")
        .config("spark.kubernetes.container.image.pullPolicy", "IfNotPresent")
        .config("spark.kubernetes.memoryOverheadFactor", "0.3")
        .config("spark.memory.fraction", "0.1")
        .config(f"fs.azure.sas.{azure_user_container_name}.{azure_account_name}.blob.core.windows.net",  azure_user_token)
        .config("spark.app.name", f"{username} (notebook)")
        .getOrCreate()
    )
    sc = SparkContext.getOrCreate()
    
    display_spark()

    
def stop_spark():
    """Stop the active Spark session and delete globals for SparkSession (spark) and SparkContext (sc).
    """

    global spark
    global sc

    if 'spark' in globals() and 'sc' in globals():

        spark.stop()

        del spark
        del sc

    display_spark()


# Make css changes to improve spark output readability

html = [
    '<style>',
    'pre { white-space: pre !important; }',
    'table.dataframe td { white-space: nowrap !important; }',
    'table.dataframe thead th:first-child, table.dataframe tbody th { display: none; }',
    '</style>',
]
display(HTML(''.join(html)))

### Assignment 2 ###

The code below demonstrates how to explore and load the data provided for the assignment from Azure Blob Storage and how to save any outputs that you generate to a separate user container.

**Key points**

- The data provided for the assignment is stored in Azure Blob Storage and outputs that you generate will be stored in Azure Blob Storage as well. Hadoop and Spark can both interact with Azure Blob Storage similar to how they interact with HDFS, but where the replication and distribution is handled by Azure instead. This makes it possible to read or write data in Azure over HTTPS where the path is prefixed by `wasbs://`.
- There are two containers, one for the data which is read only and one for any outputs that you generate,
  - `wasbs://uco-data@madsstorage002.blob.core.windows.net/`
  - `wasbs://uco-user@madsstorage002.blob.core.windows.net/`
- You can use variable interpolation to insert your global username variable into paths automatically.
  - This works for bash commands as well.

In [2]:
# Run this cell to start a spark session in this notebook

start_spark(executor_instances=2, executor_cores=2, worker_memory=4, master_memory=2)

Warning: Ignoring non-Spark config property: fs.azure.sas.campus-user.madsstorage002.blob.core.windows.net
Warning: Ignoring non-Spark config property: SPARK_DRIVER_BIND_ADDRESS
26/06/07 00:36:48 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).

### Processing Q1

In [3]:
# Write your imports here or insert cells below

from functools import reduce

import pandas as pd

from pyspark.sql import functions as F
from pyspark.sql.types import *

In [4]:
# Use the hdfs command to explore the data in Azure Blob Storage

!hdfs dfs -ls wasbs://{azure_data_container_name}@{azure_account_name}.blob.core.windows.net/msd/

Found 4 items
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/genre
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/main
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile

In [5]:
!hdfs dfs -ls wasbs://{azure_data_container_name}@{azure_account_name}.blob.core.windows.net/msd/audio/

Found 2 items
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features

In [6]:
!hdfs dfs -ls wasbs://{azure_data_container_name}@{azure_account_name}.blob.core.windows.net/msd/audio/attributes/
!hdfs dfs -ls wasbs://{azure_data_container_name}@{azure_account_name}.blob.core.windows.net/msd/audio/features/

Found 13 items
-rwxrwxrwx   1       1051 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-area-of-moments-all-v1.0.attributes.csv
-rwxrwxrwx   1        671 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-lpc-all-v1.0.attributes.csv
-rwxrwxrwx   1        484 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-methods-of-moments-all-v1.0.attributes.csv
-rwxrwxrwx   1        898 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-mfcc-all-v1.0.attributes.csv
-rwxrwxrwx   1        777 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-spectral-all-all-v1.0.attributes.csv
-rwxrwxrwx   1        777 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-spectral-derivatives-all-all-v1.0.attributes.csv
-rwxrwxrwx   1      12317 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-marsyas-timbral-v1.0.attributes.csv
-rwxrwxrwx   1       9990 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-mvd-v1.0.attributes.csv
-rwxrwxrwx   1       1390 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-rh-v1.0.attributes.csv
-rwxrwxrwx   1      34913 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-rp-v1.0.attributes.csv
-rwxrwxrwx   1       3942 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-ssd-v1.0.attributes.csv
-rwxrwxrwx   1       9990 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-trh-v1.0.attributes.csv
-rwxrwxrwx   1      28313 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-tssd-v1.0.attributes.csv
Found 13 items
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-area-of-moments-all-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-lpc-all-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-methods-of-moments-all-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-mfcc-all-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-spectral-all-all-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-spectral-derivatives-all-all-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-marsyas-timbral-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-mvd-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-rh-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-rp-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-ssd-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-trh-v1.0.csv
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-tssd-v1.0.csv

In [7]:
!hdfs dfs -ls wasbs://{azure_data_container_name}@{azure_account_name}.blob.core.windows.net/msd/audio/features/msd-jmir-area-of-moments-all-v1.0.csv/

Found 8 items
-rwxrwxrwx   1    8635110 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-area-of-moments-all-v1.0.csv/part-00000.csv.gz
-rwxrwxrwx   1    8636689 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-area-of-moments-all-v1.0.csv/part-00001.csv.gz
-rwxrwxrwx   1    8632696 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-area-of-moments-all-v1.0.csv/part-00002.csv.gz
-rwxrwxrwx   1    8635186 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-area-of-moments-all-v1.0.csv/part-00003.csv.gz
-rwxrwxrwx   1    8635805 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-area-of-moments-all-v1.0.csv/part-00004.csv.gz
-rwxrwxrwx   1    8632126 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-area-of-moments-all-v1.0.csv/part-00005.csv.gz
-rwxrwxrwx   1    8636623 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-area-of-moments-all-v1.0.csv/part-00006.csv.gz
-rwxrwxrwx   1    8259803 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-area-of-moments-all-v1.0.csv/part-00007.csv.gz

In [8]:
!hdfs dfs -ls wasbs://{azure_data_container_name}@{azure_account_name}.blob.core.windows.net/msd/genre/

Found 3 items
-rwxrwxrwx   1   11625230 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/genre/msd-MAGD-genreAssignment.tsv
-rwxrwxrwx   1    8820054 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/genre/msd-MASD-styleAssignment.tsv
-rwxrwxrwx   1   11140605 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/genre/msd-topMAGD-genreAssignment.tsv

In [9]:
!hdfs dfs -ls wasbs://{azure_data_container_name}@{azure_account_name}.blob.core.windows.net/msd/main/

Found 2 items
-rwxrwxrwx   1   58658141 2025-02-18 15:22 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/main/analysis.csv.gz
-rwxrwxrwx   1  124211304 2025-02-18 15:22 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/main/metadata.csv.gz

In [10]:
!hdfs dfs -ls wasbs://{azure_data_container_name}@{azure_account_name}.blob.core.windows.net/msd/tasteprofile/

Found 2 items
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/mismatches
drwxrwxrwx   -          0 1970-01-01 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv

In [11]:
!hdfs dfs -ls wasbs://{azure_data_container_name}@{azure_account_name}.blob.core.windows.net/msd/tasteprofile/triplets.tsv/

Found 8 items
-rwxrwxrwx   1   64020759 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv/part-00000.tsv.gz
-rwxrwxrwx   1   64038083 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv/part-00001.tsv.gz
-rwxrwxrwx   1   64077499 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv/part-00002.tsv.gz
-rwxrwxrwx   1   64102442 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv/part-00003.tsv.gz
-rwxrwxrwx   1   63998697 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv/part-00004.tsv.gz
-rwxrwxrwx   1   64049032 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv/part-00005.tsv.gz
-rwxrwxrwx   1   64064101 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv/part-00006.tsv.gz
-rwxrwxrwx   1   63788582 2024-09-13 12:00 wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile/triplets.tsv/part-00007.tsv.gz

In [12]:
# Use the hdfs command to determine the size of the data in Azure Blob Storage

!hdfs dfs -du wasbs://{azure_data_container_name}@{azure_account_name}.blob.core.windows.net/msd/

182869445    182869445    wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/main
514256719    514256719    wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/tasteprofile
31585889     31585889     wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/genre
13125647752  13125647752  wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio

In [13]:
# Use the hdfs command to determine the size of the data in Azure Blob Storage and capture the output so it can be structured and visualized

datasets = !hdfs dfs -du wasbs://{azure_data_container_name}@{azure_account_name}.blob.core.windows.net/msd/
datasets = pd.DataFrame(datasets, columns=["text"])
datasets = datasets["text"].str.extract("^(?P<SIZE>[0-9]+).*/msd/(?P<DATASET>.*)")[['DATASET', 'SIZE']]
datasets['SIZE'] = (pd.to_numeric(datasets['SIZE']) / 1024 / 1024).round(3)
datasets = datasets.sort_values(['DATASET'])

total_size = datasets['SIZE'].sum()

print(f"total size = {total_size:.3f} MB")
print(f"")
display(datasets)

total size = 13212.547 MB

        DATASET       SIZE
3         audio  12517.593
2         genre     30.123
0          main    174.398
1  tasteprofile    490.433

In [14]:
#count each dataset rows
# Define the base path for Azure Blob Storage
base_path = f"wasbs://{azure_data_container_name}@{azure_account_name}.blob.core.windows.net/msd"

print("--- Starting Row Counts ---")

# 1. Main Dataset (Metadata) - CSV GZIP format
main_df = spark.read.csv(f"{base_path}/main/metadata.csv.gz",
    header=True,  
    inferSchema=True)
print(f"1. Main (Metadata) rows: {main_df.count()}")

# 2. Genre Dataset (MAGD) - TSV format
# Note: Explicitly setting header=False because MAGD files do not contain column headers
genre_df = spark.read.csv(
    f"{base_path}/genre/msd-MAGD-genreAssignment.tsv", 
    sep='\t', 
    header=False
)
print(f"2. Genre rows: {genre_df.count()}")

# 3. Taste Profile (User play counts) - TSV format
# Note: Trailing slash is required as this is stored as a directory
tp_df = spark.read.csv(f"{base_path}/tasteprofile/triplets.tsv/", sep='\t')
print(f"3. Taste Profile rows: {tp_df.count()}")

# 4. Audio Features 
audio_names = [
    "msd-jmir-area-of-moments-all-v1.0",
    "msd-jmir-lpc-all-v1.0",
    "msd-jmir-methods-of-moments-all-v1.0",
    "msd-jmir-mfcc-all-v1.0",
    "msd-jmir-spectral-all-all-v1.0"
]

print("--- Starting row counts for the 5 audio feature datasets ---")

# Iterate through each dataset, load it from Azure Blob Storage, and count the rows
for name in audio_names:
    audio_path = f"{base_path}/audio/features/{name}.csv/"
    audio_df = spark.read.csv(audio_path)
    row_count = audio_df.count()
    print(f" {name} has: {row_count} rows")

print("--- Row counts complete! ---")

--- Starting Row Counts ---

1. Main (Metadata) rows: 1000000
2. Genre rows: 422714

3. Taste Profile rows: 48373586
--- Starting row counts for the 5 audio feature datasets ---

 msd-jmir-area-of-moments-all-v1.0 has: 994623 rows

 msd-jmir-lpc-all-v1.0 has: 994623 rows
 msd-jmir-methods-of-moments-all-v1.0 has: 994623 rows

 msd-jmir-mfcc-all-v1.0 has: 994623 rows
 msd-jmir-spectral-all-all-v1.0 has: 994623 rows
--- Row counts complete! ---

### MSD (Million Song Dataset) Directory Tree

Here is the directory structure of the audio datasets stored in Azure Blob Storage:
```text
msd/
├── main/
│   └── metadata.csv.gz
├── genre/
│   └── msd-MAGD-genreAssignment.tsv
├── tasteprofile/
│   └── triplets.tsv/   (Directory containing part files)
└── audio/
    ├── attributes/
    │   ├── msd-jmir-area-of-moments-all-v1.0.attributes.csv
    │   ├── msd-jmir-lpc-all-v1.0.attributes.csv
    │   ├── msd-jmir-methods-of-moments-all-v1.0.attributes.csv
    │   ├── msd-jmir-mfcc-all-v1.0.attributes.csv
    │   └── msd-jmir-spectral-all-all-v1.0.attributes.csv
    └── features/
        ├── msd-jmir-area-of-moments-all-v1.0.csv/   (Directory)
        ├── msd-jmir-lpc-all-v1.0.csv/               (Directory)
        ├── msd-jmir-methods-of-moments-all-v1.0.csv/(Directory)
        ├── msd-jmir-mfcc-all-v1.0.csv/              (Directory)
        └── msd-jmir-spectral-all-all-v1.0.csv/      (Directory)

### Processing Q2

In [15]:
# Specify paths based on audio feature dataset name

audio_features_name = "msd-jmir-area-of-moments-all-v1.0"

attributes_path = f'wasbs://{azure_data_container_name}@{azure_account_name}.blob.core.windows.net/msd/audio/attributes/{audio_features_name}.attributes.csv'
features_path = f'wasbs://{azure_data_container_name}@{azure_account_name}.blob.core.windows.net/msd/audio/features/{audio_features_name}.csv/'

print(attributes_path)
print(features_path)

wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/attributes/msd-jmir-area-of-moments-all-v1.0.attributes.csv
wasbs://campus-data@madsstorage002.blob.core.windows.net/msd/audio/features/msd-jmir-area-of-moments-all-v1.0.csv/

In [16]:
# Load the attributes into Spark from Azure Blob Storage using spark.read.csv

attributes = spark.read.csv(attributes_path).limit(1000)

print(type(attributes))
attributes.printSchema()
print(attributes)
attributes.show(50, False)

<class 'pyspark.sql.dataframe.DataFrame'>
root
 |-- _c0: string (nullable = true)
 |-- _c1: string (nullable = true)

DataFrame[_c0: string, _c1: string]
+----------------------------------------------------+------+
|_c0                                                 |_c1   |
+----------------------------------------------------+------+
|Area_Method_of_Moments_Overall_Standard_Deviation_1 |real  |
|Area_Method_of_Moments_Overall_Standard_Deviation_2 |real  |
|Area_Method_of_Moments_Overall_Standard_Deviation_3 |real  |
|Area_Method_of_Moments_Overall_Standard_Deviation_4 |real  |
|Area_Method_of_Moments_Overall_Standard_Deviation_5 |real  |
|Area_Method_of_Moments_Overall_Standard_Deviation_6 |real  |
|Area_Method_of_Moments_Overall_Standard_Deviation_7 |real  |
|Area_Method_of_Moments_Overall_Standard_Deviation_8 |real  |
|Area_Method_of_Moments_Overall_Standard_Deviation_9 |real  |
|Area_Method_of_Moments_Overall_Standard_Deviation_10|real  |
|Area_Method_of_Moments_Overall_Average_1            |real  |
|Area_Method_of_Moments_Overall_Average_2            |real  |
|Area_Method_of_Moments_Overall_Average_3            |real  |
|Area_Method_of_Moments_Overall_Average_4            |real  |
|Area_Method_of_Moments_Overall_Average_5            |real  |
|Area_Method_of_Moments_Overall_Average_6            |real  |
|Area_Method_of_Moments_Overall_Average_7            |real  |
|Area_Method_of_Moments_Overall_Average_8            |real  |
|Area_Method_of_Moments_Overall_Average_9            |real  |
|Area_Method_of_Moments_Overall_Average_10           |real  |
|MSD_TRACKID                                         |string|
+----------------------------------------------------+------+

In [17]:
# Load a subset of features into Spark from Azure Blob Storage using spark.read.csv

features = spark.read.csv(features_path).limit(1000)

print(type(features))
features.printSchema()
display(HTML(features.limit(10).toPandas().to_html(max_cols=5)))

<class 'pyspark.sql.dataframe.DataFrame'>
root
 |-- _c0: string (nullable = true)
 |-- _c1: string (nullable = true)
 |-- _c2: string (nullable = true)
 |-- _c3: string (nullable = true)
 |-- _c4: string (nullable = true)
 |-- _c5: string (nullable = true)
 |-- _c6: string (nullable = true)
 |-- _c7: string (nullable = true)
 |-- _c8: string (nullable = true)
 |-- _c9: string (nullable = true)
 |-- _c10: string (nullable = true)
 |-- _c11: string (nullable = true)
 |-- _c12: string (nullable = true)
 |-- _c13: string (nullable = true)
 |-- _c14: string (nullable = true)
 |-- _c15: string (nullable = true)
 |-- _c16: string (nullable = true)
 |-- _c17: string (nullable = true)
 |-- _c18: string (nullable = true)
 |-- _c19: string (nullable = true)
 |-- _c20: string (nullable = true)

In [18]:
# Load and collect the attributes and use them to create a StructType automatically

attributes_schema = StructType([
    StructField("name", StringType()),
    StructField("type", StringType()),
])
attributes = spark.read.csv(attributes_path, schema=attributes_schema)

fields = []
for row in attributes.toLocalIterator():
    if row["type"] == "real":
        fields.append(StructField(row["name"], DoubleType()))
    else:
        fields.append(StructField(row["name"], StringType()))

features_schema = StructType(fields)
features = spark.read.csv(features_path, schema=features_schema).limit(1000)

print(type(features))
features.printSchema()
display(HTML(features.limit(10).toPandas().to_html(max_cols=5)))

<class 'pyspark.sql.dataframe.DataFrame'>
root
 |-- Area_Method_of_Moments_Overall_Standard_Deviation_1: double (nullable = true)
 |-- Area_Method_of_Moments_Overall_Standard_Deviation_2: double (nullable = true)
 |-- Area_Method_of_Moments_Overall_Standard_Deviation_3: double (nullable = true)
 |-- Area_Method_of_Moments_Overall_Standard_Deviation_4: double (nullable = true)
 |-- Area_Method_of_Moments_Overall_Standard_Deviation_5: double (nullable = true)
 |-- Area_Method_of_Moments_Overall_Standard_Deviation_6: double (nullable = true)
 |-- Area_Method_of_Moments_Overall_Standard_Deviation_7: double (nullable = true)
 |-- Area_Method_of_Moments_Overall_Standard_Deviation_8: double (nullable = true)
 |-- Area_Method_of_Moments_Overall_Standard_Deviation_9: double (nullable = true)
 |-- Area_Method_of_Moments_Overall_Standard_Deviation_10: double (nullable = true)
 |-- Area_Method_of_Moments_Overall_Average_1: double (nullable = true)
 |-- Area_Method_of_Moments_Overall_Average_2: double (nullable = true)
 |-- Area_Method_of_Moments_Overall_Average_3: double (nullable = true)
 |-- Area_Method_of_Moments_Overall_Average_4: double (nullable = true)
 |-- Area_Method_of_Moments_Overall_Average_5: double (nullable = true)
 |-- Area_Method_of_Moments_Overall_Average_6: double (nullable = true)
 |-- Area_Method_of_Moments_Overall_Average_7: double (nullable = true)
 |-- Area_Method_of_Moments_Overall_Average_8: double (nullable = true)
 |-- Area_Method_of_Moments_Overall_Average_9: double (nullable = true)
 |-- Area_Method_of_Moments_Overall_Average_10: double (nullable = true)
 |-- MSD_TRACKID: string (nullable = true)

In [19]:
# Load and collect the attributes and use them to create a StructType automatically

attributes_schema = StructType([
    StructField("name", StringType()),
    StructField("type", StringType()),
])
attributes = spark.read.csv(attributes_path, schema=attributes_schema)

fields = []
i = 0
for row in attributes.toLocalIterator():
    if row["type"] == "real":
        fields.append(StructField(f"F{i:03d}", DoubleType()))
        i += 1
    else:
        fields.append(StructField("ID", StringType()))

features_schema = StructType(fields)
features = spark.read.csv(features_path, schema=features_schema).limit(1000)

print(type(features))
features.printSchema()
display(HTML(features.limit(10).toPandas().to_html(max_cols=5)))

<class 'pyspark.sql.dataframe.DataFrame'>
root
 |-- F000: double (nullable = true)
 |-- F001: double (nullable = true)
 |-- F002: double (nullable = true)
 |-- F003: double (nullable = true)
 |-- F004: double (nullable = true)
 |-- F005: double (nullable = true)
 |-- F006: double (nullable = true)
 |-- F007: double (nullable = true)
 |-- F008: double (nullable = true)
 |-- F009: double (nullable = true)
 |-- F010: double (nullable = true)
 |-- F011: double (nullable = true)
 |-- F012: double (nullable = true)
 |-- F013: double (nullable = true)
 |-- F014: double (nullable = true)
 |-- F015: double (nullable = true)
 |-- F016: double (nullable = true)
 |-- F017: double (nullable = true)
 |-- F018: double (nullable = true)
 |-- F019: double (nullable = true)
 |-- ID: string (nullable = true)

In [20]:
# Load multiple audio feature datasets using a for loop

names = [
    "msd-jmir-area-of-moments-all-v1.0",
    "msd-jmir-lpc-all-v1.0",
]
datasets = []
i = 0
for name in names:

    # Specify paths based on audio feature dataset name
    
    attributes_path = f'wasbs://{azure_data_container_name}@{azure_account_name}.blob.core.windows.net/msd/audio/attributes/{audio_features_name}.attributes.csv'
    features_path = f'wasbs://{azure_data_container_name}@{azure_account_name}.blob.core.windows.net/msd/audio/features/{audio_features_name}.csv/'

    # Load and collect the attributes and use them to create a StructType automatically
    
    attributes_schema = StructType([
        StructField("name", StringType()),
        StructField("type", StringType()),
    ])
    attributes = spark.read.csv(attributes_path, schema=attributes_schema)
    
    fields = []
    for row in attributes.toLocalIterator():
        if row["type"] == "real":
            fields.append(StructField(f"F{i:03d}", DoubleType()))
            i += 1
        else:
            fields.append(StructField("ID", StringType()))

    features_schema = StructType(fields)
    features = spark.read.csv(features_path, schema=features_schema)

    # Append to datasets so they can be merged after the loop
    
    datasets.append(features)

# Merge datasets

data = reduce(lambda x, y: x.join(y, on="ID", how="inner"), datasets)
data = data.cache()

print(type(data))
data.printSchema()
display(HTML(data.limit(10).toPandas().to_html(max_cols=5)))

26/06/07 00:37:56 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

<class 'pyspark.sql.dataframe.DataFrame'>
root
 |-- ID: string (nullable = true)
 |-- F000: double (nullable = true)
 |-- F001: double (nullable = true)
 |-- F002: double (nullable = true)
 |-- F003: double (nullable = true)
 |-- F004: double (nullable = true)
 |-- F005: double (nullable = true)
 |-- F006: double (nullable = true)
 |-- F007: double (nullable = true)
 |-- F008: double (nullable = true)
 |-- F009: double (nullable = true)
 |-- F010: double (nullable = true)
 |-- F011: double (nullable = true)
 |-- F012: double (nullable = true)
 |-- F013: double (nullable = true)
 |-- F014: double (nullable = true)
 |-- F015: double (nullable = true)
 |-- F016: double (nullable = true)
 |-- F017: double (nullable = true)
 |-- F018: double (nullable = true)
 |-- F019: double (nullable = true)
 |-- F020: double (nullable = true)
 |-- F021: double (nullable = true)
 |-- F022: double (nullable = true)
 |-- F023: double (nullable = true)
 |-- F024: double (nullable = true)
 |-- F025: double (nullable = true)
 |-- F026: double (nullable = true)
 |-- F027: double (nullable = true)
 |-- F028: double (nullable = true)
 |-- F029: double (nullable = true)
 |-- F030: double (nullable = true)
 |-- F031: double (nullable = true)
 |-- F032: double (nullable = true)
 |-- F033: double (nullable = true)
 |-- F034: double (nullable = true)
 |-- F035: double (nullable = true)
 |-- F036: double (nullable = true)
 |-- F037: double (nullable = true)
 |-- F038: double (nullable = true)
 |-- F039: double (nullable = true)

In [21]:
# Load multiple audio feature datasets using a for loop

names = [
    ("A", "msd-jmir-area-of-moments-all-v1.0"),
    ("L", "msd-jmir-lpc-all-v1.0"),
]
datasets = []
for prefix, name in names:

    # Specify paths based on audio feature dataset name
    
    attributes_path = f'wasbs://{azure_data_container_name}@{azure_account_name}.blob.core.windows.net/msd/audio/attributes/{audio_features_name}.attributes.csv'
    features_path = f'wasbs://{azure_data_container_name}@{azure_account_name}.blob.core.windows.net/msd/audio/features/{audio_features_name}.csv/'

    # Load and collect the attributes and use them to create a StructType automatically
    
    attributes_schema = StructType([
        StructField("name", StringType()),
        StructField("type", StringType()),
    ])
    attributes = spark.read.csv(attributes_path, schema=attributes_schema)
    
    fields = []
    i = 0
    for row in attributes.toLocalIterator():
        if row["type"] == "real":
            fields.append(StructField(f"{prefix}{i:03d}", DoubleType()))  # Custom prefix allows features to be easily identified
            i += 1
        else:
            fields.append(StructField("ID", StringType()))
    
    features_schema = StructType(fields)
    features = spark.read.csv(features_path, schema=features_schema)

    # Append to datasets so they can be merged after the loop
    
    datasets.append(features)

# Merge datasets

data = reduce(lambda x, y: x.join(y, on="ID", how="inner"), datasets)
data = data.cache()

print(type(data))
data.printSchema()
display(HTML(data.limit(10).toPandas().to_html(max_cols=5)))

<class 'pyspark.sql.dataframe.DataFrame'>
root
 |-- ID: string (nullable = true)
 |-- A000: double (nullable = true)
 |-- A001: double (nullable = true)
 |-- A002: double (nullable = true)
 |-- A003: double (nullable = true)
 |-- A004: double (nullable = true)
 |-- A005: double (nullable = true)
 |-- A006: double (nullable = true)
 |-- A007: double (nullable = true)
 |-- A008: double (nullable = true)
 |-- A009: double (nullable = true)
 |-- A010: double (nullable = true)
 |-- A011: double (nullable = true)
 |-- A012: double (nullable = true)
 |-- A013: double (nullable = true)
 |-- A014: double (nullable = true)
 |-- A015: double (nullable = true)
 |-- A016: double (nullable = true)
 |-- A017: double (nullable = true)
 |-- A018: double (nullable = true)
 |-- A019: double (nullable = true)
 |-- L000: double (nullable = true)
 |-- L001: double (nullable = true)
 |-- L002: double (nullable = true)
 |-- L003: double (nullable = true)
 |-- L004: double (nullable = true)
 |-- L005: double (nullable = true)
 |-- L006: double (nullable = true)
 |-- L007: double (nullable = true)
 |-- L008: double (nullable = true)
 |-- L009: double (nullable = true)
 |-- L010: double (nullable = true)
 |-- L011: double (nullable = true)
 |-- L012: double (nullable = true)
 |-- L013: double (nullable = true)
 |-- L014: double (nullable = true)
 |-- L015: double (nullable = true)
 |-- L016: double (nullable = true)
 |-- L017: double (nullable = true)
 |-- L018: double (nullable = true)
 |-- L019: double (nullable = true)

In [22]:
# Define the output path for the Parquet file in Azure Blob Storage
# It is recommended to use a descriptive and easily identifiable name
output_parquet_path = "processed_audio_features.parquet"

print(f"Preparing to save data to local cluster: {output_parquet_path}")
print("Saving... This may take a few minutes.")

# Write the DataFrame in Parquet format
data.write.mode("overwrite").parquet(output_parquet_path)

print(" Save successful! Your comprehensive feature dataset is now safely stored in your local environment!")

Preparing to save data to local cluster: processed_audio_features.parquet
Saving... This may take a few minutes.

 Save successful! Your comprehensive feature dataset is now safely stored in your local environment!

In [23]:
# Run this cell before closing the notebook or kill your spark application by hand using the link in the Spark UI

stop_spark()

26/06/07 00:38:15 WARN ExecutorPodsWatchSnapshotSource: Kubernetes client has been closed.